safe: true
url: http://thehammar.github.io
baseurl: /staging
lsi: false
highlighter: pygments
timezone: America/Los_Angeles

layouts: ./_layouts

gems: 
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - bower.json
  - CNAME
  - Gemfile
  - Gruntfile.js
  - Compression-by-Noita--license
  - LICENSE
  - node_modules/
  - package.json
  - Rakefile
  - README.md
  - vendor/

sass: 
  sass_dir: bower_components/foundation/scss
#  style: compressed

markdown: kramdown
kramdown: 
  input: GFM
  parse_block_html: true

# Site Info
name: HAMMAR
description: "A talented design firm located in Riverside, CA specializing in graphic design, marketing and printing."
vcard:
  email: "mark@thehammar.com"
  fn: "Mark Hammar"
  locality: "Riverside"
  phone: "(951) 313-7342"
  state: "CA"
  street-address: "6185 Magnolia Ave. Box #111"
  zip: "92506"

# Theme Info
thehammar:
  name: TheHammar
  description: "Jekyll theme built with Zurb Foundation 5 responsive framework."
  author: 
    name: "Remy Schrader"
    company: "RootAndFlow.com"
    url: "http://www.rootandflow.com"
  lang: en
  generator: "Built for Jekyll and published on Github Pages."
  stylesheets: 
    - /css/thehammar.css
  favicons:
    - /assets/favicon.png
  topbar:
    toggle: Menu
    right:
      - name: Home
        url: /
      - name: Mark
        url: /mark-hammar/
      - name: Contact
        url: /contact/

# Sitewide Facebook Opengraph tags
# Page specific tags can be set with "og:" in pagefile YAML FrontMatter
og:
  image: "/css/img/title-splash.jpg"
  type: website

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

