safe: true

markdown: kramdown
kramdown: 
  input: GFM
  safe: true
  parse_block_html: true
permalink: /blog/:year/:title/
relative_permalinks: true
exclude:
  - bower.json
  - CNAME
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - node_modules/
  - package.json
  - Rakefile
  - README.md
  - vendor/

layouts: ./_layouts
sass: 
  sass_dir: bower_components/foundation/scss
baseurl: "/staging"

lsi: false
highlighter: pygments

thehammar:
  name: TheHammar
  description: Jekyll theme built for TheHammar.com with Zurb Foundation 5
  author: 
    name: Remy Schrader
    company: RootAndFlow.com
    url: http://www.rootandflow.com
  lang: en
  stylesheets: 
    - /css/thehammar.css
  favicons:
    - /assets/favicon.png
  topbar:
    toggle: Menu
    right:
      - name: Home
        url: /
      - name: Mark
        url: /mark-hammar/
      - name: Contact
        url: /contact/

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
